services:
  socket-service:
    container_name: socket_service
    image: ${REGISTRY}/rt-socket-service:latest
    restart: always
    networks:
      - retrade-network
    environment:
      REDIS_URL: redis://retrade-redis:6379
      NODE_ENV: production
      PORT: 3000
      DB_HOST: retrade-database
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: chat
      MAIN_SERVICE_HOST: main-service
      MAIN_SERVICE_GRPC_PORT: 9080
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@retrade-database:5432/${DB_NAME}?schema=chat
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=retrade-network'
      - 'traefik.constraint-label=retrade-service'
      - 'traefik.http.routers.socket-service.rule=Host(`socket.${DOMAIN:-retrade.local}`)'
      - 'traefik.http.routers.socket-service.entrypoints=web'
      - 'traefik.http.services.socket-service.loadbalancer.server.port=3000'

networks:
  retrade-network:
    name: retrade-network
    external: true
