services:
  socket-services:
    image: ${REGISTRY}/rt-socket-service:latest
    build:
      context: ..
      dockerfile: Dockerfile
      tags:
        - ${REGISTRY}/rt-socket-service:${TAG}
    profiles:
      - backend
      - socket
      - build
