name: Deploy to Dev Server

on:
  push:
    branches:
      - main

jobs:
  build-images:
    name: Build Prod Images
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
      TAG: prod
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set TAG environment variable
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build and push image
        run: |
          docker compose -f .docker/compose.build.yaml --profile socket build
          docker compose -f .docker/compose.build.yaml --profile socket push
        continue-on-error: true

  deploy-dev:
    runs-on: retrade-dev
    needs: [build-images]
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
      DOMAIN: ${{ secrets.HOST_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull nightly images
        run: docker compose -f .docker/compose.yaml -p retrade-service pull
      - name: Infisical Login
        run: |
          echo "INFISICAL_TOKEN=$(infisical login --domain=${{secrets.INFISICAL_URL}} --method=universal-auth --client-id=${{secrets.INFISICAL_CLIENT_ID}} --client-secret=${{secrets.INFISICAL_CLIENT_SECRET}} --silent --plain)" >> $GITHUB_ENV
      - name: Clean Container, Image And Prepare For Deploy
        run: infisical run --env=prod --token=${{env.INFISICAL_TOKEN}} --domain=${{secrets.INFISICAL_URL}} --projectId=${{secrets.INFISICAL_PROJECT_ID}} --path=/ --watch -- docker compose -f .docker/compose.yaml -p retrade-service up -d
        continue-on-error: true

      - name: Clean Old Images
        run: docker image prune -a -f
        continue-on-error: true