name: Deploy to Dev Server

on:
  push:
    branches:
      - main

jobs:
  build-images:
    name: Build Prod Images
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
      TAG: prod
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set TAG environment variable
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build and push image
        run: |
          docker compose -f .docker/compose.build.yaml --profile socket build
          docker compose -f .docker/compose.build.yaml --profile socket push
        continue-on-error: true

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yaml
    needs: build-images
    permissions:
      contents: read
      packages: write
    with:
      actor: ${{ github.actor }}
      repository: ${{ github.repository }}
    secrets: inherit